routes/web.php
    Route::post('cancel_requests/{cancel_request}/update', 'CancelRequestsController@updateRequestStatus');
    /** end cancel requests */

    /** reports */
    Route::get('reports/products_almost_finish_reports',  'ReportsController@productsAlmostFinishedReportsEmployees')->name('supervisor.reports.products_almost_finish_reports');
    Route::get('reports/employee_products_almost_finish_reports',  'ReportsController@employeeProductsAlmostFinishedReports')->name('supervisor.reports.employee_products_almost_finish_reports');

    Route::get('reports/manual_reports',  'ReportsController@manualReportsEmployees')->name('supervisor.reports.manual_reports');
    Route::get('reports/employee_manual_reports',  'ReportsController@employeeManualReports')->name('supervisor.reports.employee_manual_reports');

    Route::get('reports/price_comparison_reports',  'ReportsController@priceComparisonReportsEmployees')->name('supervisor.reports.price_comparison_reports');
    Route::get('reports/employee_price_comparison_reports',  'ReportsController@employeePriceComparisonReports')->name('supervisor.reports.employee_price_comparison_reports');

    Route::get('reports/promotions_reports',  'ReportsController@promotionsReportsEmployees')->name('supervisor.reports.promotions_reports');
    Route::get('reports/employee_promotions_reports',  'ReportsController@employeePromotionsReports')->name('supervisor.reports.employee_promotions_reports');

    Route::get('reports/areas_reports',  'ReportsController@areasReportsEmployees')->name('supervisor.reports.areas_reports');
    Route::get('reports/employee_areas_reports',  'ReportsController@employeeAreasReports')->name('supervisor.reports.employee_areas_reports');

    Route::get('reports/reduced_prices_reports',  'ReportsController@reducedPricesReportsEmployees')->name('supervisor.reports.reduced_prices_reports');
    Route::get('reports/employee_reduced_prices_reports',  'ReportsController@employeeReducedPricesReports')->name('supervisor.reports.employee_reduced_prices_reports');

    Route::get('reports/ordinary_reports',  'ReportsController@ordinaryReportsEmployees')->name('supervisor.reports.ordinary_reports');
    Route::get('reports/employee_ordinary_reports',  'ReportsController@employeeOrdinaryReports')->name('supervisor.reports.employee_ordinary_reports');
    /** end reports */
    
    Route::group(['namespace' => 'Auth'], function () {
        // login
        Route::get('login',  'LoginController@showLoginForm')->name('supervisor.login');
        Route::post('login', 'LoginController@login');

        //logout
        Route::post('logout', 'LoginController@logout');

        // Password Reset Routes...
        Route::get('password/reset', 'ForgotPasswordController@showPasswordResetForm')->name('supervisor.password.reset');
        Route::post('password/resend_code', 'ForgotPasswordController@resendCode');
        Route::post('password/reset', 'ForgotPasswordController@reset');
    });
});

Route::group(['namespace' => 'Admin','prefix' => 'admin'], function () {

    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/error', 'AdminController@error')->name('admin.error');
    Route::get('change_lang', 'AjaxController@change_lang')->name('ajax.change_lang');
    Route::post('delete_image', 'AjaxController@deleteImage');
    Route::get('get_locations/{parent_id}', 'AjaxController@getLocations');
    Route::get('get_categories/{parent_id}', 'AjaxController@getCategories');
    Route::get('get_competitor_products/{competitor_id}', 'AjaxController@getCompetitorProducts');
    Route::post('remove_product_competitor/{competitor_id}', 'AjaxController@removeProductCompetitor');
    
    
    


    Route::get('profile', 'ProfileController@index')->name('admin.profile');
    Route::patch('profile', 'ProfileController@update');

    Route::resource('roles', 'RolesController');
    Route::post('roles/data', 'RolesController@data');

    Route::resource('admins', 'AdminsController');
    Route::post('admins/data', 'AdminsController@data');
    Route::post('admins/status/{id}', 'AdminsController@active');

    Route::resource('companies', 'CompaniesController');
    Route::post('companies/data', 'CompaniesController@data');
    Route::get('companies/status/{id}', 'CompaniesController@active');

    Route::resource('locations', 'LocationsController');
    Route::post('locations/data', 'LocationsController@data');

    Route::resource('retrieval_reasons', 'RetrievalReasonsController');
    Route::post('retrieval_reasons/data', 'RetrievalReasonsController@data');
    Route::post('retrieval_reasons/status/{id}', 'RetrievalReasonsController@active');

    Route::resource('store_types', 'StoreTypesController');
    Route::post('store_types/data', 'StoreTypesController@data');

    Route::resource('categories', 'CategoriesController');
    Route::post('categories/data', 'CategoriesController@data');

    Route::resource('competitors', 'CompetitorsController');
    Route::post('competitors/data', 'CompetitorsController@data');
    Route::post('competitors/status/{id}', 'CompetitorsController@active');

    Route::resource('competitor_products', 'CompetitorProductsController');
    Route::post('competitor_products/data', 'CompetitorProductsController@data');
    Route::post('competitor_products/status/{id}', 'CompetitorProductsController@active');

    Route::resource('products', 'ProductsController');
    Route::post('products/data', 'ProductsController@data');
    Route::post('products/status/{id}', 'ProductsController@active');

    Route::resource('promotions', 'PromotionsController');
    Route::post('promotions/data', 'PromotionsController@data');


    Route::resource('configs', 'ConfigController');
    Route::get('configs/data/table', 'ConfigController@data')->name('configs.ajax');
    Route::get('configs/delete/records', 'ConfigController@destroy')->name('configs.delete');


    Route::resource('notifications', 'NotificationController');
    Route::get('notifications/data/table', 'NotificationController@data')->name('notifications.ajax');
    Route::get('notifications/delete/records', 'NotificationController@destroy')->name('notifications.delete');
   



    Route::resource('promoDetails', 'PromoDetailController');
    Route::post('promoDetails/data/table', 'PromoDetailController@data')->name('promoDetails.ajax');
    Route::get('promoDetails/delete/records', 'PromoDetailController@destroy')->name('promoDetails.delete');


    Route::resource('stores', 'StoreController');
    Route::get('stores/map/markers', 'StoreController@map')->name('stores.map');
    Route::post('stores/data/table', 'StoreController@data')->name('stores.ajax');
    Route::get('stores/delete/records', 'StoreController@destroy')->name('stores.delete');
    Route::get('stores/active/{id}', 'StoreController@active')->name('stores.active');


   


   



    Route::resource('productCompetitors', 'ProductCompetitorController');
    Route::get('productCompetitors/data/table', 'ProductCompetitorController@data')->name('productCompetitors.ajax');
    Route::get('productCompetitors/delete/records', 'ProductCompetitorController@destroy')->name('productCompetitors.delete');


    Route::resource('productVsProducts', 'ProductVsProductController');
    Route::post('productVsProducts/data/table', 'ProductVsProductController@data')->name('productVsProducts.ajax');
    Route::get('productVsProducts/delete/records', 'ProductVsProductController@destroy')->name('productVsProducts.delete');


    Route::resource('supervisorAgents', 'SupervisorAgentController');
    Route::post('supervisorAgents/data/table', 'SupervisorAgentController@data')->name('supervisorAgents.ajax');
    Route::get('supervisorAgents/delete/records', 'SupervisorAgentController@destroy')->name('supervisorAgents.delete');


    Route::resource('tasks', 'TaskController');
    Route::post('tasks/data/table', 'TaskController@data')->name('tasks.ajax');
    Route::get('tasks/delete/records', 'TaskController@destroy')->name('tasks.delete');


    Route::resource('taskInstructions', 'TaskInstructionController');
    Route::post('taskInstructions/data/table', 'TaskInstructionController@data')->name('taskInstructions.ajax');
    Route::get('taskInstructions/delete/records', 'TaskInstructionController@destroy')->name('taskInstructions.delete');


    Route::resource('taskInstructionImages', 'TaskInstructionImageController');
    Route::get('taskInstructionImages/data/table', 'TaskInstructionImageController@data')->name('taskInstructionImages.ajax');
    Route::get('taskInstructionImages/delete/records', 'TaskInstructionImageController@destroy')->name('taskInstructionImages.delete');


    Route::resource('visits', 'VisitController');
    Route::get('visits/today/tasks', 'VisitController@todayTasks')->name("visits.today_tasks");
    Route::post('visits/data/table', 'VisitController@data')->name('visits.ajax');
    Route::post('visits/today/tasks/data', 'VisitController@todayTasksData')->name('visits.todayAjax');
    Route::get('visits/delete/records', 'VisitController@destroy')->name('visits.delete');
    Route::get('visits/{id}/edit/ajax', 'VisitController@reassignAgent')->name('visits.reassign');


    Route::resource('visitTasks', 'VisitTaskController');
    Route::post('visitTasks/data/table', 'VisitTaskController@data')->name('visitTasks.ajax');
    Route::get('visitTasks/delete/records', 'VisitTaskController@destroy')->name('visitTasks.delete');


    Route::resource('visitStores', 'VisitStoreController');
    Route::post('visitStores/data/table', 'VisitStoreController@data')->name('visitStores.ajax');
    Route::get('visitStores/delete/records', 'VisitStoreController@destroy')->name('visitStores.delete');


    Route::resource('visitAgents', 'VisitAgentController');
    Route::post('visitAgents/data/table', 'VisitAgentController@data')->name('visitAgents.ajax');

app/Models/Location.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

class Location extends MyModel {

    use SoftDeletes;

    protected $table = "locations";
    
    

    public static function getAll($parent_id = 0) {
        $data =  static::join('location_translations', function($query){
                            $query->on('locations.id', '=', 'location_translations.location_id')
                             ->where('location_translations.locale', static::getLangCode());
                        })
                        ->where('locations.parent_id',$parent_id);
        $data = self::checkCreatedBy($data, 'locations')
                        ->select('locations.*', 'location_translations.title')
                        ->get();
        return $data;
    }

    public function childs() {
        return $this->hasMany(Location::class, 'parent_id');
    }

    public function translations() {
        return $this->hasMany(LocationTranslation::class, 'location_id');
    }


    public static function transformAdmin($item)
    {
        $transformer = new \stdClass();
        $transformer->id = en_de_crypt($item->id);
        $transformer->title = $item->title;

        return $transformer;
    }

   

    protected static function boot() {
        parent::boot();

        static::deleting(function($location) {
            
            
        });

        static::deleted(function($location) {
            
        });
    }

}

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use App\Scopes\CompanyScope;
use App\Traits\Basic;
use Illuminate\Contracts\Encryption\DecryptException;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class BackendController extends Controller
{

    use Basic;
   
    protected $lang_code;
    protected $user;
    protected $data = array();

    public function __construct() {
        
        $this->middleware('auth');
        //$this->middleware('role');
        $this->getCookieLangAndSetLocale();
        $this->user = Auth::user();
        $this->data['user'] = $this->user;
        $this->data['languages'] = $this->languages;
    }

    
    protected function getCookieLangAndSetLocale()
    {
        if (\Cookie::get('AdminLang') !== null) {
            try {
                $this->lang_code = \Crypt::decrypt(\Cookie::get('AdminLang'));
            } catch (DecryptException $ex) {
                $this->lang_code = 'en';
            }
        } else {
            $this->lang_code = 'en';
        }
        $this->data['lang_code'] = $this->lang_code;
        app()->setLocale($this->lang_code);
    }
    public function uploadFile(Request $request,$field , $thum = true)
    {
        if ($request->hasFile($field)) {
            $uploaded = upload($request->file($field), $thum);
            if ($thum) {
                $file = $uploaded['thum'];
            } else {
                $file = $uploaded['img'];
            }
            return $file;
        } else {
            return "";
        }
    }

    protected function checkCreatedBy($data,$table_name) {
        $column = $table_name.".created_by";
        $super_parent_id = explode(",", $this->user->parents_id)[0];
        
        if ($super_parent_id) {
            $data = $data->where(function ($query) use ($column,$super_parent_id) {
                $query->where($column, $super_parent_id)
                    ->orWhereIn($column, function ($query, $super_parent_id) {
                        $query->select('id')->from('users')
                            ->whereRaw('FIND_IN_SET(?,parents_ids) > 0', $super_parent_id);
                    });
            });
        }
        else{
            $data = $data->where(function ($query) use ($column) {
                $query->where($column, $this->user->id)
                      ->orWhereIn($column, function ($query) {
                        $query->select('id')->from('users')
                            ->whereRaw('FIND_IN_SET(?,parents_ids) > 0', $this->user->id);
                    });
            });
        }
                               
        return $data;
    }

    protected function _view($main_content, $type = 'backend') {
        $main_content = "main_content/$type/$main_content";
        return view($main_content, $this->data);
    }

    public function err404()
    {
        return $this->_view('err404');
    }


}

resources/views/main_content/backend/locations/create.blade.php
@extends('layouts.backend')

@section('pageTitle',_lang('app.add_location'))

@section('breadcrumb')
<li><a href="{{url('admin')}}">{{_lang('app.dashboard')}}</a> <i class="fa fa-circle"></i></li>
<li><a href="{{route('locations.index')}}">{{_lang('app.countries')}}</a> <i class="fa fa-circle"></i></li>
@if($path)
{!!$path!!}
@endif
<li><span>{{_lang('app.create')}}</span></li>
@endsection

@section('js')
<script src="{{url('public/backend/js')}}/locations.js" type="text/javascript"></script>
@endsection
@section('content')
<form role="form"  id="addEditLocationsForm" enctype="multipart/form-data">
    {{ csrf_field() }}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{_lang('app.title') }}</h3>
        </div>
        <div class="panel-body">


            <div class="form-body">
                <input type="hidden" name="id" id="id" value="0">

                @foreach ($languages as $key => $value)

                <div class="form-group form-md-line-input col-md-6">
                    <input type="text" class="form-control" id="title[{{ $key }}]" name="title[{{ $key }}]" value="">
                    <label for="title">{{_lang('app.title') }} {{ _lang('app. '.$value.'') }}</label>
                    <span class="help-block"></span>
                </div>

                @endforeach


            </div>
        </div>
        <div class="panel-footer text-center">
            <button type="button" class="btn btn-info submit-form">{{_lang('app.save') }}</button>
        </div>

    </div>


</form>
<script>
var new_lang = {

};
var new_config = {
    parent_id: "{{$parent_id}}"
};

</script>
@endsection

resources/views/main_content/backend/locations/edit.blade.php
@extends('layouts.backend')

@section('pageTitle',_lang('app.edit_location'))

@section('breadcrumb')
<li><a href="{{url('admin')}}">{{_lang('app.dashboard')}}</a> <i class="fa fa-circle"></i></li>
<li><a href="{{route('locations.index')}}">{{_lang('app.countries')}}</a> <i class="fa fa-circle"></i></li>
@if($path)
{!!$path!!}
@endif
<li><span>{{_lang('app.edit')}}</span></li>
@endsection


@section('js')
<script src="{{url('public/backend/js')}}/locations.js" type="text/javascript"></script>
@endsection
@section('content')
<form role="form"  id="addEditLocationsForm" enctype="multipart/form-data">
    {{ csrf_field() }}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{_lang('app.title') }}</h3>
        </div>
        <div class="panel-body">
            <div class="form-body">
                <input type="hidden" name="id" id="id" value="{{ en_de_crypt($location->id) }}">
                @foreach ($languages as $key => $value)
                <div class="form-group form-md-line-input col-md-6">
                    <input type="text" class="form-control" id="title[{{ $key }}]" name="title[{{ $key }}]" value="{{ $translations["$key"]->title }}">
                    <label for="title">{{_lang('app.title') }} {{ _lang('app. '.$value.'') }}</label>
                    <span class="help-block"></span>
                </div>
                @endforeach
            </div>
        </div>
        <div class="panel-footer text-center">
            <button type="button" class="btn btn-info submit-form">{{_lang('app.save') }}</button>
        </div>

    </div>



</form>
<script>
var new_lang = {

};
var new_config = {
    parent_id: "{{$parent_id}}"
};

</script>
@endsection

resources/views/main_content/backend/locations/index.blade.php
@extends('layouts.backend')

@section('pageTitle', _lang('app.countries'))

@section('breadcrumb')
<li><a href="{{url('admin')}}">{{_lang('app.dashboard')}}</a> <i class="fa fa-circle"></i></li>
@if($path)
<li><a href="{{route('locations.index')}}">{{_lang('app.countries')}}</a> <i class="fa fa-circle"></i></li>
{!!$path!!}
@else
<li><span> {{_lang('app.countries')}}</span></li>
@endif

@endsection

@section('js')
<script src="{{url('public/backend/js')}}/locations.js" type="text/javascript"></script>
@endsection

@section('content')
@if (session()->has('error_message'))
<div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
    <strong>{{_lang('app.error')}}!</strong> {{session()->get('error_message')}}.
</div>
@endif
 {{ csrf_field() }}
<div class = "panel panel-default">
    <div class = "panel-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-6">
                    <div class="btn-group">
                        <a class="btn green" style="margin-bottom: 40px;" href = "{{ route('locations.create') }}?parent={{ $parent_id }}" onclick="">{{ _lang('app.add_new')}}<i class="fa fa-plus"></i> </a>
                    </div>
                </div>
            </div>
        </div>
        <table class= "table table-striped table-bordered table-hover table-checkable order-column dataTable no-footer">
            <thead>
                <tr>
                    <th>{{_lang('app.title')}}</th>
                    <th>{{_lang('app.options')}}</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
        </table>

        <!--Table Wrapper Finish-->
    </div>
</div>
<script>
var new_lang = {

};
var new_config = {
    parent_id: "{{$parent_id}}"
};
</script>
@endsection