routes/web.php
    Route::get('notifications/delete/records', 'NotificationController@destroy')->name('notifications.delete');
   



    Route::resource('promoDetails', 'PromoDetailController');
    Route::post('promoDetails/data/table', 'PromoDetailController@data')->name('promoDetails.ajax');
    Route::get('promoDetails/delete/records', 'PromoDetailController@destroy')->name('promoDetails.delete');


    Route::resource('stores', 'StoreController');
    Route::get('stores/map/markers', 'StoreController@map')->name('stores.map');
    Route::post('stores/data/table', 'StoreController@data')->name('stores.ajax');
    Route::get('stores/delete/records', 'StoreController@destroy')->name('stores.delete');
    Route::get('stores/active/{id}', 'StoreController@active')->name('stores.active');


   


   



    Route::resource('productCompetitors', 'ProductCompetitorController');
    Route::get('productCompetitors/data/table', 'ProductCompetitorController@data')->name('productCompetitors.ajax');
    Route::get('productCompetitors/delete/records', 'ProductCompetitorController@destroy')->name('productCompetitors.delete');


    Route::resource('productVsProducts', 'ProductVsProductController');
    Route::post('productVsProducts/data/table', 'ProductVsProductController@data')->name('productVsProducts.ajax');
    Route::get('productVsProducts/delete/records', 'ProductVsProductController@destroy')->name('productVsProducts.delete');


    Route::resource('supervisorAgents', 'SupervisorAgentController');
    Route::post('supervisorAgents/data/table', 'SupervisorAgentController@data')->name('supervisorAgents.ajax');
    Route::get('supervisorAgents/delete/records', 'SupervisorAgentController@destroy')->name('supervisorAgents.delete');


    Route::resource('tasks', 'TaskController');
    Route::post('tasks/data/table', 'TaskController@data')->name('tasks.ajax');
    Route::get('tasks/delete/records', 'TaskController@destroy')->name('tasks.delete');


    Route::resource('taskInstructions', 'TaskInstructionController');
    Route::post('taskInstructions/data/table', 'TaskInstructionController@data')->name('taskInstructions.ajax');
    Route::get('taskInstructions/delete/records', 'TaskInstructionController@destroy')->name('taskInstructions.delete');


    Route::resource('taskInstructionImages', 'TaskInstructionImageController');
    Route::get('taskInstructionImages/data/table', 'TaskInstructionImageController@data')->name('taskInstructionImages.ajax');
    Route::get('taskInstructionImages/delete/records', 'TaskInstructionImageController@destroy')->name('taskInstructionImages.delete');


    Route::resource('visits', 'VisitController');
    Route::get('visits/today/tasks', 'VisitController@todayTasks')->name("visits.today_tasks");
    Route::post('visits/data/table', 'VisitController@data')->name('visits.ajax');
    Route::post('visits/today/tasks/data', 'VisitController@todayTasksData')->name('visits.todayAjax');
    Route::get('visits/delete/records', 'VisitController@destroy')->name('visits.delete');
    Route::get('visits/{id}/edit/ajax', 'VisitController@reassignAgent')->name('visits.reassign');


    Route::resource('visitTasks', 'VisitTaskController');
    Route::post('visitTasks/data/table', 'VisitTaskController@data')->name('visitTasks.ajax');
    Route::get('visitTasks/delete/records', 'VisitTaskController@destroy')->name('visitTasks.delete');


    Route::resource('visitStores', 'VisitStoreController');
    Route::post('visitStores/data/table', 'VisitStoreController@data')->name('visitStores.ajax');
    Route::get('visitStores/delete/records', 'VisitStoreController@destroy')->name('visitStores.delete');


    Route::resource('visitAgents', 'VisitAgentController');
    Route::post('visitAgents/data/table', 'VisitAgentController@data')->name('visitAgents.ajax');
    Route::get('visitAgents/delete/records', 'VisitAgentController@destroy')->name('visitAgents.delete');


    Route::resource('visitDetails', 'VisitDetailController');
    Route::post('visitDetails/data/table', 'VisitDetailController@data')->name('visitDetails.ajax');
    Route::get('visitDetails/delete/records', 'VisitDetailController@destroy')->name('visitDetails.delete');


    Route::resource('visitCancels', 'VisitCancelController');
    Route::post('visitCancels/data/table', 'VisitCancelController@data')->name('visitCancels.ajax');
    Route::get('visitCancels/delete/records', 'VisitCancelController@destroy')->name('visitCancels.delete');


    Route::resource('visitTaskDetails', 'VisitTaskDetailController');
    Route::get('visitTaskDetails/data/table', 'VisitTaskDetailController@data')->name('visitTaskDetails.ajax');
    Route::get('visitTaskDetails/delete/records', 'VisitTaskDetailController@destroy')->name('visitTaskDetails.delete');


    Route::resource('visitTaskDetailImages', 'VisitTaskDetailImageController');
    Route::get('visitTaskDetailImages/data/table', 'VisitTaskDetailImageController@data')->name('visitTaskDetailImages.ajax');
    Route::get('visitTaskDetailImages/delete/records', 'VisitTaskDetailImageController@destroy')->name('visitTaskDetailImages.delete');


    Route::resource('visitTaskReturnDetails', 'VisitTaskReturnDetailController');
    Route::get('visitTaskReturnDetails/data/table', 'VisitTaskReturnDetailController@data')->name('visitTaskReturnDetails.ajax');
    Route::get('visitTaskReturnDetails/delete/records', 'VisitTaskReturnDetailController@destroy')->name('visitTaskReturnDetails.delete');


    Route::resource('visitTaskInventoryDetails', 'VisitTaskInventoryDetailController');
    Route::get('visitTaskInventoryDetails/data/table', 'VisitTaskInventoryDetailController@data')->name('visitTaskInventoryDetails.ajax');
    Route::get('visitTaskInventoryDetails/delete/records', 'VisitTaskInventoryDetailController@destroy')->name('visitTaskInventoryDetails.delete');


    Route::resource('visitTaskAreaDetails', 'VisitTaskAreaDetailController');
    Route::get('visitTaskAreaDetails/data/table', 'VisitTaskAreaDetailController@data')->name('visitTaskAreaDetails.ajax');
    Route::get('visitTaskAreaDetails/delete/records', 'VisitTaskAreaDetailController@destroy')->name('visitTaskAreaDetails.delete');


    Route::resource('visitTaskBillDetails', 'VisitTaskBillDetailController');
    Route::get('visitTaskBillDetails/data/table', 'VisitTaskBillDetailController@data')->name('visitTaskBillDetails.ajax');
    Route::get('visitTaskBillDetails/delete/records', 'VisitTaskBillDetailController@destroy')->name('visitTaskBillDetails.delete');


    Route::resource('visitTaskPromoDetails', 'VisitTaskPromoDetailController');
    Route::get('visitTaskPromoDetails/data/table', 'VisitTaskPromoDetailController@data')->name('visitTaskPromoDetails.ajax');
    Route::get('visitTaskPromoDetails/delete/records', 'VisitTaskPromoDetailController@destroy')->name('visitTaskPromoDetails.delete');


    Route::resource('userAttendances', 'UserAttendanceController');
    Route::get('userAttendances/data/table', 'UserAttendanceController@data')->name('userAttendances.ajax');
    Route::get('userAttendances/delete/records', 'UserAttendanceController@destroy')->name('userAttendances.delete');


    Route::resource('agentHolidays', 'AgentHolidayController');
    Route::get('agentHolidays/data/table', 'AgentHolidayController@data')->name('agentHolidays.ajax');
    Route::get('agentHolidays/delete/records', 'AgentHolidayController@destroy')->name('agentHolidays.delete');


    Route::resource('agentRates', 'AgentRateController');
    Route::post('agentRates/data/table', 'AgentRateController@data')->name('agentRates.ajax');
    Route::get('agentRates/delete/records', 'AgentRateController@destroy')->name('agentRates.delete');


    Route::resource('visitTaskCancels', 'VisitTaskCancelController');
    Route::get('visitTaskCancels/data/table', 'VisitTaskCancelController@data')->name('visitTaskCancels.ajax');
    Route::get('visitTaskCancels/delete/records', 'VisitTaskCancelController@destroy')->name('visitTaskCancels.delete');


   


    Route::resource('permissions', 'PermissionController');
    Route::get('permissions/data/table', 'PermissionController@data')->name('permissions.ajax');
    Route::get('permissions/delete/records', 'PermissionController@destroy')->name('permissions.delete');


    Route::resource('permissionRoles', 'PermissionRoleController');
    Route::get('permissionRoles/data/table', 'PermissionRoleController@data')->name('permissionRoles.ajax');
    Route::get('permissionRoles/delete/records', 'PermissionRoleController@destroy')->name('permissionRoles.delete');


    Route::resource('reports', 'ReportController');
    Route::get('reports/data/table', 'ReportController@data')->name('reports.ajax');
    Route::get('reports/delete/records', 'ReportController@destroy')->name('reports.delete');


    Route::resource('reportDetails', 'ReportDetailController');
    Route::get('reportDetails/data/table', 'ReportDetailController@data')->name('reportDetails.ajax');
    Route::get('reportDetails/delete/records', 'ReportDetailController@destroy')->name('reportDetails.delete');


    Route::resource('reportDetailImages', 'ReportDetailImageController');
    Route::get('reportDetailImages/data/table', 'ReportDetailImageController@data')->name('reportDetailImages.ajax');
    Route::get('reportDetailImages/delete/records', 'ReportDetailImageController@destroy')->name('reportDetailImages.delete');


    Route::resource('reportCompetitors', 'ReportCompetitorController');
    Route::get('reportCompetitors/data/table', 'ReportCompetitorController@data')->name('reportCompetitors.ajax');
    Route::get('reportCompetitors/delete/records', 'ReportCompetitorController@destroy')->name('reportCompetitors.delete');


    Route::resource('agents', 'AgentsController');
    Route::post('agents/data/table', 'AgentsController@data')->name('agents.ajax');
    Route::get('agents/delete/records', 'AgentsController@destroy')->name('agents.delete');

app/Http/Controllers/Admin/VisitStoreController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateVisitStoreRequest;
use App\Http\Requests\UpdateVisitStoreRequest;
use App\Repositories\VisitStoreRepository;
use Illuminate\Http\Request;
use Flash;
use DataTables;
use App\Models\VisitStore;
use function Helper\Common\imageUrl;

class VisitStoreController extends AppBaseController
{
    /** @var  VisitStoreRepository */
    private $visitStoreRepository;

    public function __construct(VisitStoreRepository $visitStoreRepo)
    {
        parent::__construct();
        $this->visitStoreRepository = $visitStoreRepo;
    }







    /**
     * Display a listing of the VisitStore.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
    /*
        $this->visitStoreRepository->pushCriteria(new RequestCriteria($request));
        $visitStores = $this->visitStoreRepository->all();
        */

        return view('visit_stores.index');
        /*return view('visit_stores.index')
             ->with('visitStores', $visitStores);*/
    }



    /**
     * Show the form for creating a new VisitStore.
     *
     * @return Response
     */
    public function create()
    {
        return view('visit_stores.create');
    }

    /**
     * Store a newly created VisitStore in storage.
     *
     * @param CreateVisitStoreRequest $request
     *
     * @return Response
     */
    public function store(CreateVisitStoreRequest $request)
    {

        $input = $request->request->all();

        $input['image'] = $this->uploadFile($request,"image",true);

        $visitStore = $this->visitStoreRepository->create($input);

        Flash::success('تم حفظ البيانات بنجاح');

        return redirect(route('visitStores.index'));
    }

    /**
     * Display the specified VisitStore.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $visitStore = $this->visitStoreRepository->findWithoutFail($id);

        if (empty($visitStore)) {
            Flash::error('عفوا خطأ في البيانات برجاء محاولة مره اخري');

            return redirect(route('visitStores.index'));
        }

        return view('visit_stores.show')->with('visitStore', $visitStore);
    }

    /**
     * Show the form for editing the specified VisitStore.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $visitStore = $this->visitStoreRepository->findWithoutFail($id);

        if (empty($visitStore)) {
            Flash::error('عفوا خطأ في البيانات برجاء محاولة مره اخري');

            return redirect(route('visitStores.index'));
        }

        return view('visit_stores.edit')->with('visitStore', $visitStore);
    }

    /**
     * Update the specified VisitStore in storage.
     *
     * @param  int              $id
     * @param UpdateVisitStoreRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateVisitStoreRequest $request)
    {


        $visitStore = $this->visitStoreRepository->findWithoutFail($id);

        if (empty($visitStore)) {
            Flash::error('عفوا خطأ في البيانات برجاء محاولة مره اخري');

            return redirect(route('visitStores.index'));
        }


        $input = $request->request->all();

        if($request->hasFile("image"))
            $input['image'] = $this->uploadFile($request,"image",true);

        $visitStore = $this->visitStoreRepository->update($input, $id);

        Flash::success('تم تعديل البيانات بنجاح');

        return redirect(route('visitStores.index'));
    }

    /**
     * Remove the specified VisitStore from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy(Request $request)
    {
        /*
         if($request->ids != null AND count($request->ids) > 0)
         {
             foreach ($request->ids as $id)
             {
                 $this->visitStoreRepository->delete($id);
             }
         }
         else
         {
             Flash::error('برجاء تحديد بيانات المراد حذفها');
             return redirect(route('visitStores.index'));
         }
        Flash::success('تم الحذف بنجاح');

        return redirect(route('visitStores.index'));
         */

        if($request->ids != null AND count($request->ids) > 0)
        {

            foreach ($request->ids as $id)
            {
                $this->visitStoreRepository->delete($id);
            }
        }
        else
        {
            $data['message'] = 'برجاء تحديد بيانات المراد حذفها';
            $data['success'] = false;
            return $data;
        }
        $data['message'] = 'تم الحذف بنجاح';
        $data['success'] = true;
        return $data;

    }

    public function data() {
            $items = VisitStore::select();

            return DataTables::eloquent($items)
                ->addColumn('options', function (VisitStore $item) {
                    $back = ' <div class="btn-group">';
                    $back .= '
                        <a href="'. route('visitStores.show' ,[$item->id]).'" class="btn btn-light waves-effect waves-light m-1"><i class="fa fa-eye"></i></a>
                        <a href="'. route('visitStores.edit' ,[$item->id]).'" class="btn btn-light waves-effect waves-light m-1"><i class="fa fa-edit"></i></a>
                    </div>';
                    return $back;
                })
                /*
                 ->addColumn("active",function(VisitStore $item){
                    if($item->active == 1)
                    {
                        $back = '<a class="btn btn-warning" onclick="changeActive(this)" data-id="'.$item->id.'">';
                        $back.= "اقفال التفعيل"."</a>";
                    }
                    else
                    {
                        $back = '<a class="btn btn-success" onclick="changeActive(this)" data-id="'.$item->id.'">';
                        $back.= "تفعيل"."</a>";
                    }
                    return $back;
                 })
                 ->editColumn('image', function (VisitStore $item) {
                    $back = ' <img src= "'.imageUrl($item->image).'" class="img-circle" style="width:75px;height:75px;" >';
                    return $back;
                 })
                 */
                ->editColumn("id",function($item){
                    $back = '<div class="checkbox checkbox-danger">';
                    $back.='
                        <input id="'.$item->id.'" type="checkbox" name="ids[]" value="'.$item->id.'">';
                    $back .= '
                        <label for="'.$item->id.'">  </label>
                    </div>';

                    return $back;
                })
                ->rawColumns(['options', 'active'])
                ->escapeColumns([])
                ->make(true);
        }


}

resources/views/main_content/backend/visit_stores/create.blade.php
@extends('layouts.app')

@section('content')

 <div class="container-fluid">

            <!-- Breadcrumb-->
            <div class="row pt-2 pb-2">
                <div class="col-sm-9">
                    <h4 class="page-title">Visit Stores</h4>
                </div>
            </div>
            <!-- End Breadcrumb-->

            <div class="row">
                <div class="col-lg-12">

                    <div class="card">
                        <div class="card-body">

                           @include('adminlte-templates::common.errors')

                           {!! Form::open(['route' => 'visitStores.store','files' => true,"class"=>"floating-labels"]) !!}

                           @include('visit_stores.fields')

                           {!! Form::close() !!}

                        </div>
                    </div>

                </div>
            </div>

        </div>


@endsection

resources/views/main_content/backend/visit_stores/edit.blade.php
@extends('layouts.app')

@section('content')


 <div class="container-fluid">

            <!-- Breadcrumb-->
            <div class="row pt-2 pb-2">
                <div class="col-sm-9">
                    <h4 class="page-title">Visit Stores</h4>
                </div>
            </div>
            <!-- End Breadcrumb-->

            <div class="row">
                <div class="col-lg-12">

                    <div class="card">
                        <div class="card-body">

                           @include('adminlte-templates::common.errors')

                          {!! Form::model($visitStore, ['route' => ['visitStores.update', $visitStore->id],'files' => true, 'method' => 'patch',"class"=>"floating-labels"]) !!}

                          @include('visit_stores.fields')

                          {!! Form::close() !!}
                        </div>
                    </div>

                </div>
            </div>

        </div>

@endsection

resources/views/main_content/backend/visit_stores/fields.blade.php
 <div class="form-body">
<!-- Visit Id Field -->
     <div class="form-group row">
     {!! Form::label('visit_id', 'Visit Id:',['class' => 'col-sm-2 col-form-label']) !!}
    <div class="col-sm-10">
    {!! Form::text('visit_id', null, ['class' => 'form-control','id'=>"visit_id","required"]) !!}
    </div>
 </div>

<!-- Store Id Field -->
     <div class="form-group row">
     {!! Form::label('store_id', 'Store Id:',['class' => 'col-sm-2 col-form-label']) !!}
    <div class="col-sm-10">
    {!! Form::text('store_id', null, ['class' => 'form-control','id'=>"store_id","required"]) !!}
    </div>
 </div>

<!-- Status Field -->
     <div class="form-group row">
     {!! Form::label('status', 'Status:',['class' => 'col-sm-2 col-form-label']) !!}
    <div class="col-sm-10">
    {!! Form::text('status', null, ['class' => 'form-control','id'=>"status","required"]) !!}
    </div>
 </div>

</div>


 <div class="form-group row">
     <label class="col-sm-2 col-form-label"></label>
     <div class="col-sm-10">
         <button type="submit" class="btn btn-white px-5"><i class="icon-settings"></i> حفظ</button>
         <a href="{!! route('visitStores.index') !!}" class="btn btn-light waves-effect waves-light m-1">الغاء</a>

     </div>
 </div>

resources/views/main_content/backend/visit_stores/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <!-- Breadcrumb-->
        <div class="row pt-2 pb-2">
            <div class="col-sm-9">
                <h4 class="page-title">Visit Stores</h4>
            </div>
            <div class="col-sm-3">
                <div class="btn-group float-sm-right">
                    <button type="button" class="btn btn-light waves-effect waves-light"><i class="fa fa-cog mr-1"></i> Setting</button>
                    <button type="button" class="btn btn-light dropdown-toggle dropdown-toggle-split waves-effect waves-light" data-toggle="dropdown">
                        <span class="caret"></span>
                    </button>
                    <div class="dropdown-menu">
                        <a  href="{!! route('visitStores.create') !!}" class="dropdown-item">اضافة جديد</a>
                        <a onclick="event.preventDefault(); deleteRecord('visitStores',datatable)" class="dropdown-item">حذف</a>
                    </div>
                </div>
            </div>
        </div>

    {!! Form::open(['route' => ['visitStores.delete'], 'method' => 'delete','id' => 'delete-form']) !!}

    {{ csrf_field() }}

        <!-- End Breadcrumb-->

                        @include('visit_stores.table')


        {!! Form::close() !!}



    </div>
    <!-- End container-fluid-->
@endsection

resources/views/main_content/backend/visit_stores/show.blade.php
@extends('layouts.app')

@section('content')


  <div class="container-fluid">

        <!-- Breadcrumb-->
        <div class="row pt-2 pb-2">
            <div class="col-sm-9">
                <h4 class="page-title">Visit Stores</h4>
            </div>
        </div>
        <!-- End Breadcrumb-->

        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">
                        @include('visit_stores.show_fields')
                        <a href="{!! route('visitStores.index') !!}" class="btn btn-light waves-effect waves-light m-1">رجوع</a>

                    </div>
                </div>

            </div>
        </div>

    </div>


@endsection

resources/views/main_content/backend/visit_stores/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $visitStore->id !!}</p>
</div>

<!-- Visit Id Field -->
<div class="form-group">
    {!! Form::label('visit_id', 'Visit Id:') !!}
    <p>{!! $visitStore->visit_id !!}</p>
</div>

<!-- Store Id Field -->
<div class="form-group">
    {!! Form::label('store_id', 'Store Id:') !!}
    <p>{!! $visitStore->store_id !!}</p>
</div>

<!-- Status Field -->
<div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    <p>{!! $visitStore->status !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $visitStore->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $visitStore->updated_at !!}</p>
</div>

resources/views/main_content/backend/visit_stores/table.blade.php
 <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header"><i class="fa fa-table"></i> Data Table Example</div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="default-datatable" class="dataTable table table-bordered">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Visit Id</th>
        <th>Store Id</th>
        <th>Status</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>


                            <script>
                                $( document ).ready(function() {
                                    datatable = $('.dataTable').dataTable({
                                        //"processing": true,
                                        "serverSide": true,
                                        "ajax": {
                                            "url": "{{route('visitStores.ajax')}}",
                                            "type": "GET",
                                        },
                                        "columns": [
                                            {"data": "id"},
               {"data": "visit_id"},
               {"data": "store_id"},
               {"data": "status"},

                                            {"data": "options", orderable: false, searchable: false}
                                        ],
                                        "order": [
                                            [0, "desc"]
                                        ],
                                        //"oLanguage": {"sUrl": config.url + '/datatable-lang-' + "ar" + '.json'}

                                    });
                                });
                            </script>

                        </div>
                    </div>
                </div>
            </div>
        </div><!-- End Row-->